CREATE DATABASE IF NOT EXISTS blogdb;
USE blogdb;

CREATE TABLE IF NOT EXISTS Blogs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Creating a new user
CREATE USER IF NOT EXISTS 'remote'@'%' IDENTIFIED BY 'burlywood995';

-- Granting privileges to the user
GRANT ALL PRIVILEGES ON blogdb.* TO 'remote'@'%' WITH GRANT OPTION;

-- Applying changes
FLUSH PRIVILEGES;
